{% set name = "dftbplus" %}
{% set version = "24.1" %}

package:
  name: {{ name|lower }}-python
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 776d83779666e06bf2930c3b1665cdb8e7409b8003e33e0178fbae8b47f5e0b1

build:
  number: 1
  script: {{ PYTHON }} -m pip install tools/pythonapi -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - dftbplus

test:
  requires:
    - python {{ python_min }}
  imports:
    - dftbplus

about:
  home: https://{{ name }}.org
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - LICENSE
    - COPYING
    - COPYING.LESSER
  summary: DFTB+ general package for performing fast atomistic simulations
  doc_url: https://{{ name }}-recipes.readthedocs.io
  dev_url: https://github.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - aradi
    - awvwgk
    - bhourahine
