{% set name = "dftbplus" %}
{% set version = "21.2" %}

package:
  name: {{ name|lower }}-python
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: e73aa698ff951b59f7fe2ea027b292bae16abf545c9fdbb11b5b5127f04a3c10

build:
  number: 0
  script: {{ PYTHON }} -m pip install tools/pythonapi -vv
  noarch: python

requirements:
  host:
    - python >=3.3
    - pip
  run:
    - python >=3.3
    - numpy
    - dftbplus

test:
  imports:
    - dftbplus

about:
  home: https://{{ name }}.org
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - LICENSE
    - COPYING
    - COPYING.LESSER
  summary: DFTB+ general package for performing fast atomistic simulations
  doc_url: https://{{ name }}-recipes.readthedocs.io
  dev_url: https://github.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - aradi
    - awvwgk
    - bhourahine
