{% set name = "dftbplus" %}
{% set version = "21.1" %}

package:
  name: {{ name|lower }}-python
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 31d5a488843a05d8589a375307a2832c1fc938f9f7d830c45a062726659e7b0a

build:
  number: 0
  script: {{ PYTHON }} -m pip install tools/pythonapi -vv
  noarch: python

requirements:
  host:
    - python >=3.3
    - pip
  run:
    - python >=3.3
    - numpy
    - dftbplus

test:
  imports:
    - dftbplus

about:
  home: https://{{ name }}.org
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - LICENSE
    - COPYING
    - COPYING.LESSER
  summary: DFTB+ general package for performing fast atomistic simulations
  doc_url: https://{{ name }}-recipes.readthedocs.io
  dev_url: https://github.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - aradi
    - awvwgk
    - bhourahine
